# Generated by Django 2.2.7 on 2020-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=64)),
                ('village', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField()),
                ('govt_scheme_enroll', models.BooleanField()),
                ('crop_insurance', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='produce',
            name='produceName',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='quantity',
        ),
        migrations.AddField(
            model_name='produce',
            name='fruits',
            field=models.CharField(default='NaN', max_length=64),
        ),
        migrations.AddField(
            model_name='produce',
            name='grains',
            field=models.CharField(default='NaN', max_length=64),
        ),
        migrations.AddField(
            model_name='produce',
            name='oilseeds',
            field=models.CharField(default='NaN', max_length=64),
        ),
        migrations.AddField(
            model_name='produce',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='sale_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='unit',
            field=models.CharField(default='NaN', max_length=4),
        ),
        migrations.AddField(
            model_name='produce',
            name='vegetables',
            field=models.CharField(default='NaN', max_length=64),
        ),
    ]
