# Generated by Django 2.2.7 on 2020-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_auto_20200412_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='fruits',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='produce',
            name='grains',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='produce',
            name='oilseeds',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='produce',
            name='unit',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='produce',
            name='vegetables',
            field=models.CharField(default='', max_length=64),
        ),
    ]
