# Generated by Django 2.2.7 on 2020-04-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0008_auto_20200412_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='grains_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='grains_qty',
            field=models.IntegerField(default=0),
        ),
    ]
