# Generated by Django 2.2.7 on 2020-04-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0011_auto_20200413_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='fruits',
            new_name='fruit',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='fruits_price',
            new_name='fruit_price',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='fruits_qty',
            new_name='fruit_qty',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='fruits_unit',
            new_name='fruit_unit',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='fruits_update_date',
            new_name='fruit_update_date',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='grains',
            new_name='grain',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='grains_price',
            new_name='grain_price',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='grains_qty',
            new_name='grain_qty',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='grains_unit',
            new_name='grain_unit',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='grains_update_date',
            new_name='grain_update_date',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='oilseeds',
            new_name='oilseed',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='oilseeds_price',
            new_name='oilseed_price',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='oilseeds_qty',
            new_name='oilseed_qty',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='oilseeds_unit',
            new_name='oilseed_unit',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='oilseeds_update_date',
            new_name='oilseed_update_date',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='vegetables',
            new_name='vegetable',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='vegetables_price',
            new_name='vegetable_price',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='vegetables_qty',
            new_name='vegetable_qty',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='vegetables_unit',
            new_name='vegetable_unit',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='vegetables_update_date',
            new_name='vegetable_update_date',
        ),
    ]
