# Generated by Django 2.2.7 on 2020-04-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0012_auto_20200413_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
