# Generated by Django 2.2.7 on 2020-04-13 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0015_auto_20200413_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(default='', max_length=64)),
                ('fruit_qty', models.IntegerField(default=0)),
                ('fruit_unit', models.CharField(default='', max_length=5)),
                ('fruit_price', models.IntegerField(default=0)),
                ('fruit_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fruit_comment', models.TextField(default='')),
                ('farmer', models.ForeignKey(on_delete='DO_NOTHING', to='farmerapp.Farmer')),
            ],
            options={
                'verbose_name_plural': 'Fruit Produce',
            },
        ),
        migrations.CreateModel(
            name='GrainProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.CharField(default='', max_length=64)),
                ('grain_qty', models.IntegerField(default=0)),
                ('grain_unit', models.CharField(default='', max_length=5)),
                ('grain_price', models.IntegerField(default=0)),
                ('grain_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grain_comment', models.TextField(default='')),
                ('farmer', models.ForeignKey(on_delete='DO_NOTHING', to='farmerapp.Farmer')),
            ],
            options={
                'verbose_name_plural': 'Grain Produce',
            },
        ),
        migrations.CreateModel(
            name='OilseedProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oilseed', models.CharField(default='', max_length=64)),
                ('oilseed_qty', models.IntegerField(default=0)),
                ('oilseed_unit', models.CharField(default='', max_length=5)),
                ('oilseed_price', models.IntegerField(default=0)),
                ('oilseed_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('oilseed_comment', models.TextField(default='')),
                ('farmer', models.ForeignKey(on_delete='DO_NOTHING', to='farmerapp.Farmer')),
            ],
            options={
                'verbose_name_plural': 'Oilseed Produce',
            },
        ),
        migrations.CreateModel(
            name='VegetableProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable', models.CharField(default='', max_length=64)),
                ('vegetable_qty', models.IntegerField(default=0)),
                ('vegetable_unit', models.CharField(default='', max_length=5)),
                ('vegetable_price', models.IntegerField(default=0)),
                ('vegetable_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vegetable_comment', models.TextField(default='')),
                ('farmer', models.ForeignKey(on_delete='DO_NOTHING', to='farmerapp.Farmer')),
            ],
            options={
                'verbose_name_plural': 'Vegetable Produce',
            },
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
