# Generated by Django 2.2.10 on 2020-04-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0016_auto_20200413_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitproduce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmerapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='grainproduce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmerapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='oilseedproduce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmerapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='vegetableproduce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmerapp.Farmer'),
        ),
    ]
