# Generated by Django 2.2.7 on 2020-04-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0005_auto_20200412_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
