# Generated by Django 2.2.7 on 2020-04-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0006_produce_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produce',
            options={'verbose_name_plural': 'Produce'},
        ),
    ]
