# Generated by Django 2.2.7 on 2020-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0014_produce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='farmerapp.Farmer'),
        ),
    ]
